import tailwindcss from '@tailwindcss/vite'

const title = 'Rufus Maiwald | Portfolio'
const description = 'Rufus Maiwald ist Java- und Webentwickler und studiert Informatik in München. Hier erfährst du mehr über ihn.'

export default defineNuxtConfig({

  modules: [
    '@nuxt/eslint',
    '@nuxtjs/color-mode',
    '@nuxtjs/google-fonts',
    '@nuxtjs/i18n',
    '@vite-pwa/nuxt',
    '@nuxt/content'
  ],

  app: {
    head: {
      title,
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: description },
        // Previously generated by @nuxtjs/pwa's meta module.
        { name: 'author', content: 'Rufus Maiwald' },
        { name: 'theme-color', content: '#18181b' },
        { name: 'mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' },
        { name: 'apple-mobile-web-app-title', content: title },
        { property: 'og:type', content: 'website' },
        { property: 'og:title', content: title },
        { property: 'og:site_name', content: title },
        { property: 'og:description', content: description },
        { property: 'og:url', content: 'https://rufusmai.com' },
        { property: 'og:image', content: 'https://rufusmai.com/og_img.png' },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { property: 'og:image:type', content: 'image/png' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:creator', content: '@rufusmai' }
      ],
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
      ],
      script: [
        // Umami, proxied through /stats so it is served from this domain.
        {
          'src': '/stats/script.js',
          'defer': true,
          'data-website-id': '1d1ae607-8a41-427e-b78f-028b000d5461',
          'data-domains': 'rufusmai.com'
        }
      ]
    },
    pageTransition: {
      name: 'page',
      mode: 'out-in'
    }
  },

  css: [
    '@/assets/css/tailwind.css'
  ],

  colorMode: {
    preference: 'system',
    fallback: 'dark',
    classSuffix: ''
  },
  compatibilityDate: '2025-07-15',

  nitro: {
    // Serve Umami first-party from /stats, matching the previous vercel.json rewrite.
    vercel: {
      config: {
        routes: [
          {
            src: '/stats/(.*)',
            dest: 'https://analytics.rufusmai.com/$1'
          }
        ]
      }
    },
    devProxy: {
      '/stats': {
        target: 'https://analytics.rufusmai.com',
        changeOrigin: true
      }
    }
  },

  vite: {
    plugins: [
      tailwindcss()
    ]
  },

  eslint: {
    config: {
      // Keeps the code style this project was already written in.
      stylistic: {
        commaDangle: 'never',
        braceStyle: '1tbs'
      }
    }
  },

  googleFonts: {
    families: {
      'Noto+Sans+SC': [400, 600, 700]
    },
    display: 'swap'
  },

  i18n: {
    baseUrl: 'https://rufusmai.com',
    locales: [
      { code: 'de', name: 'Deutsch', language: 'de', file: 'de.js' },
      { code: 'en', name: 'English', language: 'en', file: 'en.js' }
    ],
    defaultLocale: 'de',
    strategy: 'no_prefix',
    detectBrowserLanguage: false,
    lazy: true
  },

  pwa: {
    registerType: 'autoUpdate',
    manifest: {
      name: 'Rufus Maiwald Portfolio',
      short_name: 'rufusmai',
      description,
      background_color: '#18181b',
      theme_color: '#18181b',
      icons: [
        { src: '/icon.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' }
      ]
    },
    workbox: {
      globPatterns: ['**/*.{js,css,html,png,svg,ico,webmanifest}'],
      skipWaiting: true,
      clientsClaim: true,
      runtimeCaching: [
        {
          urlPattern: /^https:\/\/api\.github\.com\/users\/[^/]+\/repos/,
          handler: 'StaleWhileRevalidate',
          options: {
            cacheName: 'gh-projects',
            broadcastUpdate: {
              options: {
                headersToCheck: ['content-length', 'etag', 'last-modified']
              }
            }
          }
        }
      ]
    }
  }
})
